import { MigrationInterface, QueryRunner } from "typeorm";

export class EsquemaInicial1789063616253 implements MigrationInterface {
    name = 'EsquemaInicial1789063616253'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TYPE "public"."usuarios_estado_enum" AS ENUM('activo', 'inactivo', 'bloqueado', 'pendiente')`);
        await queryRunner.query(`CREATE TABLE "usuarios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "fecha_actualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "email" text NOT NULL, "hash_password" text NOT NULL, "nombres" text NOT NULL, "apellidos" text NOT NULL, "telefono" text, "estado" "public"."usuarios_estado_enum" NOT NULL DEFAULT 'pendiente', "email_verificado_en" TIMESTAMP WITH TIME ZONE, "ultimo_acceso_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_d7281c63c176e152e4c531594a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_446adfc18b35418aac32ae0b7b" ON "usuarios"  ("email") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "fecha_actualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "clave" text NOT NULL, "nombre" text NOT NULL, "descripcion" text, "es_sistema" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a6c91cc0373d07c0884887ae51" ON "roles"  ("clave") `);
        await queryRunner.query(`CREATE TABLE "permisos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clave" text NOT NULL, "descripcion" text, "grupo" text, CONSTRAINT "PK_3127bd9cfeb13ae76186d0d9b38" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0da1398fc247170cac89e49205" ON "permisos"  ("clave") `);
        await queryRunner.query(`CREATE TABLE "roles_permisos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rol_id" uuid NOT NULL, "permiso_id" uuid NOT NULL, CONSTRAINT "UQ_0e1dbe0449ae37ef1b31b0d9474" UNIQUE ("rol_id", "permiso_id"), CONSTRAINT "PK_558aeeacf6cfc38b06944ab4038" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dc3cfbcce511233d4bef92d7e3" ON "roles_permisos"  ("rol_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef10d9983fcb45f0024cc7000d" ON "roles_permisos"  ("permiso_id") `);
        await queryRunner.query(`CREATE TABLE "usuarios_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "usuario_id" uuid NOT NULL, "rol_id" uuid NOT NULL, "institucion_id" uuid, "asignado_por" uuid, "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_28b7dce276998a01eab1e96f24a" UNIQUE ("usuario_id", "rol_id", "institucion_id"), CONSTRAINT "PK_28de221731be7761ba1b165df08" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2c14b9e5e2d0cf077fa4dd3350" ON "usuarios_roles"  ("usuario_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_425dfd009aeeee0c08af9a67a3" ON "usuarios_roles"  ("rol_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_aeab9942770118a43c775d15f1" ON "usuarios_roles"  ("institucion_id") `);
        await queryRunner.query(`CREATE TABLE "sesiones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "usuario_id" uuid NOT NULL, "user_agent" text, "ip" inet, "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ultima_actividad_en" TIMESTAMP WITH TIME ZONE, "expira_en" TIMESTAMP WITH TIME ZONE NOT NULL, "revocada_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_e4237ef09f1dc217c1660f23253" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_be14eb22d2e8fbf2ca6c3fe0d5" ON "sesiones"  ("usuario_id") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sesion_id" uuid NOT NULL, "hash_token" text NOT NULL, "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "expira_en" TIMESTAMP WITH TIME ZONE NOT NULL, "revocado_en" TIMESTAMP WITH TIME ZONE, "reemplazado_por" uuid, CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ca207b81ff4fdef23d67064c1" ON "refresh_tokens"  ("sesion_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b61ca8d3b37ca11928995f2277" ON "refresh_tokens"  ("hash_token") `);
        await queryRunner.query(`CREATE TYPE "public"."llaves_api_estado_enum" AS ENUM('activa', 'revocada', 'expirada')`);
        await queryRunner.query(`CREATE TABLE "llaves_api" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "fecha_actualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "nombre" text NOT NULL, "nombre_desarrollador" text, "propietario_usuario_id" uuid, "prefijo_llave" text NOT NULL, "hash_llave" text NOT NULL, "limite_tasa" integer, "estado" "public"."llaves_api_estado_enum" NOT NULL DEFAULT 'activa', "ultimo_uso_en" TIMESTAMP WITH TIME ZONE, "expira_en" TIMESTAMP WITH TIME ZONE, "creada_por" uuid, CONSTRAINT "PK_da3c125903255274168ddf2a4bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f291436142c2b81fa077a77f15" ON "llaves_api"  ("propietario_usuario_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_308b63c6ca11d126e7abc6052c" ON "llaves_api"  ("prefijo_llave") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1bfaf1ece297bf10a420b96fd5" ON "llaves_api"  ("hash_llave") `);
        await queryRunner.query(`CREATE TABLE "llaves_api_scopes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "llave_api_id" uuid NOT NULL, "scope" text NOT NULL, CONSTRAINT "UQ_c6da15aa2412d67f1ae6c3913f7" UNIQUE ("llave_api_id", "scope"), CONSTRAINT "PK_d39854bf440562036493bf8b8fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_105947105ef5ba0ed4a934b397" ON "llaves_api_scopes"  ("llave_api_id") `);
        await queryRunner.query(`CREATE TABLE "departamentos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" text, "nombre" text NOT NULL, CONSTRAINT "PK_6d34dc0415358a018818c683c1e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f48b6363c3ee466eaa21dae234" ON "departamentos"  ("codigo") `);
        await queryRunner.query(`CREATE TABLE "municipios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "departamento_id" uuid NOT NULL, "codigo" text, "nombre" text NOT NULL, CONSTRAINT "PK_10d04b4b4e39ba40240b61e919d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cfc60523878116f625631f0e25" ON "municipios"  ("departamento_id") `);
        await queryRunner.query(`CREATE TYPE "public"."instituciones_estado_enum" AS ENUM('borrador', 'en_revision', 'aprobado', 'publicado', 'archivado')`);
        await queryRunner.query(`CREATE TABLE "instituciones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "fecha_actualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "slug" text NOT NULL, "nombre" text NOT NULL, "siglas" text, "url_logo" text, "sitio_web" text, "descripcion" text, "estado" "public"."instituciones_estado_enum" NOT NULL DEFAULT 'borrador', "publicado_en" TIMESTAMP WITH TIME ZONE, "creado_por" uuid, "actualizado_por" uuid, CONSTRAINT "PK_4be89b4d1536e4588a73f2247d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_26432f4088d2b4315c77342120" ON "instituciones"  ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."instituciones_contactos_tipo_enum" AS ENUM('telefono', 'correo', 'whatsapp', 'sitio_web', 'otro')`);
        await queryRunner.query(`CREATE TABLE "instituciones_contactos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "institucion_id" uuid NOT NULL, "tipo" "public"."instituciones_contactos_tipo_enum" NOT NULL, "valor" text NOT NULL, "etiqueta" text, "orden" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_e768f1eb615a0ee50014d7abc8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e4b6487ae036dbac881c969ed3" ON "instituciones_contactos"  ("institucion_id") `);
        await queryRunner.query(`CREATE TABLE "instituciones_direcciones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "institucion_id" uuid NOT NULL, "departamento_id" uuid, "municipio_id" uuid, "direccion" text, "referencia" text, "latitud" numeric(10,7), "longitud" numeric(10,7), "es_principal" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_434ac7792ca58993962e3622a99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7f62270c608af6385526ab2935" ON "instituciones_direcciones"  ("institucion_id") `);
        await queryRunner.query(`CREATE TYPE "public"."categorias_estado_enum" AS ENUM('borrador', 'en_revision', 'aprobado', 'publicado', 'archivado')`);
        await queryRunner.query(`CREATE TABLE "categorias" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "fecha_actualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "slug" text NOT NULL, "nombre" text NOT NULL, "url_icono" text, "descripcion" text, "orden" integer NOT NULL DEFAULT '0', "estado" "public"."categorias_estado_enum" NOT NULL DEFAULT 'borrador', CONSTRAINT "PK_3886a26251605c571c6b4f861fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d7c32fbaefae4a73773e52c316" ON "categorias"  ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."categorias_traducciones_estado_enum" AS ENUM('borrador', 'en_revision', 'aprobada', 'publicada')`);
        await queryRunner.query(`CREATE TABLE "categorias_traducciones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "fecha_actualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "categoria_id" uuid NOT NULL, "idioma_id" uuid NOT NULL, "nombre" text NOT NULL, "descripcion" text, "estado" "public"."categorias_traducciones_estado_enum" NOT NULL DEFAULT 'borrador', "traducido_por" uuid, "revisado_por" uuid, CONSTRAINT "UQ_381f8f78897aa36607c42fc8b6c" UNIQUE ("categoria_id", "idioma_id"), CONSTRAINT "PK_1bd95993618c70fce054c56d9d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6bf3298f3a0a23605b1587cfb7" ON "categorias_traducciones"  ("categoria_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_527ab82a85e09fba0470d9c4dc" ON "categorias_traducciones"  ("idioma_id") `);
        await queryRunner.query(`CREATE TYPE "public"."tramites_estado_enum" AS ENUM('borrador', 'en_revision', 'aprobado', 'publicado', 'archivado')`);
        await queryRunner.query(`CREATE TYPE "public"."tramites_modo_ejecucion_enum" AS ENUM('solo_informacion', 'enlace_externo', 'formulario_en_linea', 'totalmente_digital', 'hibrido')`);
        await queryRunner.query(`CREATE TYPE "public"."tramites_modalidad_enum" AS ENUM('en_linea', 'presencial', 'mixto')`);
        await queryRunner.query(`CREATE TYPE "public"."tramites_tipo_costo_enum" AS ENUM('gratuito', 'fijo', 'variable', 'desconocido')`);
        await queryRunner.query(`CREATE TYPE "public"."tramites_tiempo_respuesta_unidad_enum" AS ENUM('minutos', 'horas', 'dias_habiles', 'dias_calendario', 'semanas', 'meses')`);
        await queryRunner.query(`CREATE TYPE "public"."tramites_calidad_datos_enum" AS ENUM('completo', 'parcial', 'necesita_revision', 'verificado')`);
        await queryRunner.query(`CREATE TYPE "public"."tramites_tipo_fuente_enum" AS ENUM('oficial', 'traducida', 'aportada_usuario', 'pendiente_verificar')`);
        await queryRunner.query(`CREATE TABLE "tramites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "fecha_actualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "public_id" text NOT NULL, "slug" text NOT NULL, "codigo" text, "nombre" text NOT NULL, "descripcion_corta" text, "descripcion" text, "institucion_id" uuid NOT NULL, "estado" "public"."tramites_estado_enum" NOT NULL DEFAULT 'borrador', "resultado" text, "modo_ejecucion" "public"."tramites_modo_ejecucion_enum" NOT NULL DEFAULT 'solo_informacion', "modalidad" "public"."tramites_modalidad_enum", "dirigido_a" text, "disponible_en_linea" boolean NOT NULL DEFAULT false, "url_externa" text, "url_fuente_oficial" text, "tipo_costo" "public"."tramites_tipo_costo_enum" NOT NULL DEFAULT 'desconocido', "costo" numeric(12,2), "moneda" text NOT NULL DEFAULT 'GTQ', "tiempo_respuesta_valor" integer, "tiempo_respuesta_unidad" "public"."tramites_tiempo_respuesta_unidad_enum", "tiempo_respuesta_texto" text, "fecha_inicio" date, "fecha_vencimiento" date, "periodo_validez" text, "departamento_id" uuid, "municipio_id" uuid, "calidad_datos" "public"."tramites_calidad_datos_enum" NOT NULL DEFAULT 'parcial', "tipo_fuente" "public"."tramites_tipo_fuente_enum" NOT NULL DEFAULT 'oficial', "source_url" text, "source_updated_at" TIMESTAMP WITH TIME ZONE, "importado_en" TIMESTAMP WITH TIME ZONE, "ultima_verificacion_en" TIMESTAMP WITH TIME ZONE, "verificado_por" uuid, "vistas" bigint NOT NULL DEFAULT '0', "publicado_en" TIMESTAMP WITH TIME ZONE, "creado_por" uuid, "actualizado_por" uuid, CONSTRAINT "PK_163627d5c5cf7c25be3877451fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5516120ac0363cd07913429117" ON "tramites"  ("public_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1c80b0eec4e61714935290872e" ON "tramites"  ("slug") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0e98a13d29d97c5dbbd38012ea" ON "tramites"  ("codigo") `);
        await queryRunner.query(`CREATE INDEX "IDX_5eec71d25c15ca645497b9deff" ON "tramites"  ("institucion_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d4be5d74c734cfa8533f70fbb2" ON "tramites"  ("estado") `);
        await queryRunner.query(`CREATE TABLE "tramites_categorias" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tramite_id" uuid NOT NULL, "categoria_id" uuid NOT NULL, "es_principal" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_5b2c79c2c2e59df6f24ae4d3aae" UNIQUE ("tramite_id", "categoria_id"), CONSTRAINT "PK_a70c2931324d7a855742b04968c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1c00d9a6655a1324e8e8d00d7c" ON "tramites_categorias"  ("tramite_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ed31569a06d7fb6079d05faaba" ON "tramites_categorias"  ("categoria_id") `);
        await queryRunner.query(`CREATE TYPE "public"."tramites_traducciones_estado_enum" AS ENUM('borrador', 'en_revision', 'aprobada', 'publicada')`);
        await queryRunner.query(`CREATE TABLE "tramites_traducciones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "fecha_actualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tramite_id" uuid NOT NULL, "idioma_id" uuid NOT NULL, "nombre" text NOT NULL, "descripcion_corta" text, "descripcion" text, "descripcion_requisitos" text, "descripcion_pasos" text, "seo_titulo" text, "seo_descripcion" text, "estado" "public"."tramites_traducciones_estado_enum" NOT NULL DEFAULT 'borrador', "traducido_por" uuid, "revisado_por" uuid, CONSTRAINT "UQ_3933a0c36154ca903ebe0259e22" UNIQUE ("tramite_id", "idioma_id"), CONSTRAINT "PK_797100cc309dcdedb409e925903" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a451860420a30fcff54859804f" ON "tramites_traducciones"  ("tramite_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_85680d7cb03faf0049b16ab78e" ON "tramites_traducciones"  ("idioma_id") `);
        await queryRunner.query(`CREATE TYPE "public"."tramites_historial_estado_estado_anterior_enum" AS ENUM('borrador', 'en_revision', 'aprobado', 'publicado', 'archivado')`);
        await queryRunner.query(`CREATE TYPE "public"."tramites_historial_estado_estado_nuevo_enum" AS ENUM('borrador', 'en_revision', 'aprobado', 'publicado', 'archivado')`);
        await queryRunner.query(`CREATE TABLE "tramites_historial_estado" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tramite_id" uuid NOT NULL, "estado_anterior" "public"."tramites_historial_estado_estado_anterior_enum", "estado_nuevo" "public"."tramites_historial_estado_estado_nuevo_enum" NOT NULL, "cambiado_por" uuid, "nota" text, "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5c9917cc5c7b156769e13a18564" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_31b34a542bfefa0741820fe82f" ON "tramites_historial_estado"  ("tramite_id") `);
        await queryRunner.query(`CREATE TYPE "public"."tramites_requisitos_tipo_enum" AS ENUM('documento', 'pago', 'condicion', 'otro')`);
        await queryRunner.query(`CREATE TABLE "tramites_requisitos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tramite_id" uuid NOT NULL, "titulo" text NOT NULL, "descripcion" text, "tipo" "public"."tramites_requisitos_tipo_enum" NOT NULL DEFAULT 'documento', "es_obligatorio" boolean NOT NULL DEFAULT true, "cantidad" integer, "requiere_archivo" boolean NOT NULL DEFAULT false, "tipos_archivo_permitidos" text array, "dias_validez" integer, "notas" text, "orden" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_a0dd5280f784711cb7defe0a3ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b8be3ac0ad1b1e0e9b77b6d735" ON "tramites_requisitos"  ("tramite_id") `);
        await queryRunner.query(`CREATE TYPE "public"."tramites_pasos_parte_responsable_enum" AS ENUM('ciudadano', 'institucion', 'tercero', 'sistema')`);
        await queryRunner.query(`CREATE TYPE "public"."tramites_pasos_canal_enum" AS ENUM('en_linea', 'presencial', 'telefono', 'correo', 'mixto')`);
        await queryRunner.query(`CREATE TABLE "tramites_pasos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tramite_id" uuid NOT NULL, "orden" integer NOT NULL DEFAULT '0', "titulo" text NOT NULL, "descripcion" text, "parte_responsable" "public"."tramites_pasos_parte_responsable_enum" NOT NULL DEFAULT 'ciudadano', "tiempo_estimado" text, "canal" "public"."tramites_pasos_canal_enum", "ubicacion" text, "requiere_pago" boolean NOT NULL DEFAULT false, "requiere_documento" boolean NOT NULL DEFAULT false, "url_externa" text, CONSTRAINT "PK_643b075703ff7310fb451ac98cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c9ed0201065b146538ae7b9178" ON "tramites_pasos"  ("tramite_id") `);
        await queryRunner.query(`CREATE TABLE "tramites_normativas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tramite_id" uuid NOT NULL, "titulo" text NOT NULL, "tipo" text, "numero" text, "url" text, "fecha" date, "extracto" text, "orden" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_3222742c3aa19af74d63f162cf3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5cd69d7d48ac0625ef0c933555" ON "tramites_normativas"  ("tramite_id") `);
        await queryRunner.query(`CREATE TYPE "public"."tramites_enlaces_tipo_enum" AS ENUM('tramite_en_linea', 'fuente_oficial', 'informacion', 'formulario_descarga', 'otro')`);
        await queryRunner.query(`CREATE TABLE "tramites_enlaces" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tramite_id" uuid NOT NULL, "tipo" "public"."tramites_enlaces_tipo_enum" NOT NULL DEFAULT 'informacion', "titulo" text NOT NULL, "url" text NOT NULL, "orden" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_9dc69acf9bfc1f66c380c279f66" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_42eb2e58870c320be7df4616ba" ON "tramites_enlaces"  ("tramite_id") `);
        await queryRunner.query(`CREATE TYPE "public"."tramites_costos_tipo_costo_enum" AS ENUM('gratuito', 'fijo', 'variable', 'desconocido')`);
        await queryRunner.query(`CREATE TABLE "tramites_costos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tramite_id" uuid NOT NULL, "concepto" text NOT NULL, "tipo_costo" "public"."tramites_costos_tipo_costo_enum" NOT NULL DEFAULT 'fijo', "monto" numeric(12,2), "moneda" text NOT NULL DEFAULT 'GTQ', "descripcion" text, "orden" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_06864201feb98a9ae83bd5e75f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_284e34f923eed08301debee313" ON "tramites_costos"  ("tramite_id") `);
        await queryRunner.query(`CREATE TYPE "public"."tramites_tiempos_unidad_enum" AS ENUM('minutos', 'horas', 'dias_habiles', 'dias_calendario', 'semanas', 'meses')`);
        await queryRunner.query(`CREATE TABLE "tramites_tiempos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tramite_id" uuid NOT NULL, "concepto" text NOT NULL, "valor" integer, "unidad" "public"."tramites_tiempos_unidad_enum", "descripcion" text, CONSTRAINT "PK_70982627b3ce30c9a01ff0c2169" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e35c18a08cc37cce6e3f334d79" ON "tramites_tiempos"  ("tramite_id") `);
        await queryRunner.query(`CREATE TYPE "public"."tramites_disponibilidad_canal_enum" AS ENUM('en_linea', 'presencial', 'telefono', 'correo', 'mixto')`);
        await queryRunner.query(`CREATE TABLE "tramites_disponibilidad" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tramite_id" uuid NOT NULL, "departamento_id" uuid, "municipio_id" uuid, "institucion_id" uuid, "canal" "public"."tramites_disponibilidad_canal_enum", "notas" text, "activo" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b5d2b1a7b9adc8fa5c71fd02f7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f03904a0ec8011ca602f6c6c7f" ON "tramites_disponibilidad"  ("tramite_id") `);
        await queryRunner.query(`CREATE TABLE "tramites_versiones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tramite_id" uuid NOT NULL, "version" integer NOT NULL, "snapshot" jsonb NOT NULL, "creado_por" uuid, "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "publicado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_91edbb31839d370e9cd98be6967" UNIQUE ("tramite_id", "version"), CONSTRAINT "PK_5c6992c0487f7814de2be473508" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0f8d4b0664a1e6b338aae9a171" ON "tramites_versiones"  ("tramite_id") `);
        await queryRunner.query(`CREATE TYPE "public"."tramites_integraciones_tipo_integracion_enum" AS ENUM('rest', 'soap', 'webhook', 'polling', 'archivo')`);
        await queryRunner.query(`CREATE TYPE "public"."tramites_integraciones_tipo_auth_enum" AS ENUM('ninguno', 'api_key', 'oauth2', 'basic', 'token')`);
        await queryRunner.query(`CREATE TABLE "tramites_integraciones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "fecha_actualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tramite_id" uuid NOT NULL, "tipo_integracion" "public"."tramites_integraciones_tipo_integracion_enum" NOT NULL, "base_url" text, "endpoint" text, "tipo_auth" "public"."tramites_integraciones_tipo_auth_enum" NOT NULL DEFAULT 'ninguno', "configuracion" jsonb, "activo" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_9c9c8bf8bd4f6d470eaf1a2ef25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e144260cf0bbc965925854716d" ON "tramites_integraciones"  ("tramite_id") `);
        await queryRunner.query(`CREATE TABLE "idiomas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" text NOT NULL, "nombre" text NOT NULL, "nombre_nativo" text, "es_maya" boolean NOT NULL DEFAULT false, "activo" boolean NOT NULL DEFAULT true, "orden" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_a9bfe9f03f167c8a3365b3c8331" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cbc4d734c634c8078ec93e5a85" ON "idiomas"  ("codigo") `);
        await queryRunner.query(`CREATE TYPE "public"."tramites_videos_senas_estado_enum" AS ENUM('borrador', 'en_revision', 'aprobado', 'publicado')`);
        await queryRunner.query(`CREATE TABLE "tramites_videos_senas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "fecha_actualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tramite_id" uuid NOT NULL, "lengua_senas" text NOT NULL DEFAULT 'LENSEGUA', "titulo" text NOT NULL, "descripcion" text, "url_video" text NOT NULL, "url_miniatura" text, "duracion_segundos" integer, "transcripcion" text, "estado" "public"."tramites_videos_senas_estado_enum" NOT NULL DEFAULT 'borrador', "creado_por" uuid, "aprobado_por" uuid, CONSTRAINT "PK_eda2bf3cc8e2dfc32e6edd46661" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c835f3a2b9097b7a7d01f10719" ON "tramites_videos_senas"  ("tramite_id") `);
        await queryRunner.query(`CREATE TYPE "public"."tramites_recursos_accesibilidad_tipo_enum" AS ENUM('subtitulos', 'transcripcion', 'audio', 'texto_simplificado', 'lectura_facil', 'otro')`);
        await queryRunner.query(`CREATE TYPE "public"."tramites_recursos_accesibilidad_estado_enum" AS ENUM('borrador', 'en_revision', 'aprobado', 'publicado')`);
        await queryRunner.query(`CREATE TABLE "tramites_recursos_accesibilidad" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "fecha_actualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tramite_id" uuid NOT NULL, "tipo" "public"."tramites_recursos_accesibilidad_tipo_enum" NOT NULL, "titulo" text NOT NULL, "contenido" text, "url" text, "idioma_id" uuid, "estado" "public"."tramites_recursos_accesibilidad_estado_enum" NOT NULL DEFAULT 'borrador', "creado_por" uuid, CONSTRAINT "PK_369210b6ff649b4e3816a60e774" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_03173731e3505b43c33eed386a" ON "tramites_recursos_accesibilidad"  ("tramite_id") `);
        await queryRunner.query(`CREATE TABLE "formularios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "fecha_actualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tramite_id" uuid NOT NULL, "titulo" text NOT NULL, "descripcion" text, "esta_activo" boolean NOT NULL DEFAULT true, "version_actual_id" uuid, "creado_por" uuid, CONSTRAINT "REL_47c769c3b433d16c9f24c2bf7a" UNIQUE ("tramite_id"), CONSTRAINT "PK_99d35e86697a78044541773bd67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_47c769c3b433d16c9f24c2bf7a" ON "formularios"  ("tramite_id") `);
        await queryRunner.query(`CREATE TYPE "public"."formularios_versiones_estado_enum" AS ENUM('borrador', 'publicada', 'archivada')`);
        await queryRunner.query(`CREATE TABLE "formularios_versiones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "formulario_id" uuid NOT NULL, "version" integer NOT NULL, "estado" "public"."formularios_versiones_estado_enum" NOT NULL DEFAULT 'borrador', "notas" text, "publicado_por" uuid, "creado_por" uuid, "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "publicado_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_2946746872d73067e838d0447cb" UNIQUE ("formulario_id", "version"), CONSTRAINT "PK_935ab0f1713a44ea9a73c90d400" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b5869ca4c77e7dffaa0d0e1e75" ON "formularios_versiones"  ("formulario_id") `);
        await queryRunner.query(`CREATE TABLE "formularios_secciones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "formulario_version_id" uuid NOT NULL, "clave" text NOT NULL, "titulo" text NOT NULL, "descripcion" text, "orden" integer NOT NULL DEFAULT '0', "activo" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_f24be48fa7bcdc2d0dfc31226ac" UNIQUE ("formulario_version_id", "clave"), CONSTRAINT "PK_f91e4c449949bb6c53f009fa424" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_70f19441de0564b6ab281c2851" ON "formularios_secciones"  ("formulario_version_id") `);
        await queryRunner.query(`CREATE TYPE "public"."formularios_campos_tipo_enum" AS ENUM('texto', 'texto_area', 'numero', 'decimal', 'fecha', 'fecha_hora', 'hora', 'email', 'telefono', 'url', 'booleano', 'seleccion', 'seleccion_multiple', 'radio', 'casilla', 'archivo', 'imagen', 'pdf', 'video', 'firma', 'direccion', 'departamento', 'municipio', 'nacionalidad', 'dpi', 'texto_enriquecido', 'repetidor', 'grupo')`);
        await queryRunner.query(`CREATE TABLE "formularios_campos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "formulario_version_id" uuid NOT NULL, "seccion_id" uuid, "clave" text NOT NULL, "etiqueta" text NOT NULL, "descripcion" text, "placeholder" text, "tipo" "public"."formularios_campos_tipo_enum" NOT NULL, "es_requerido" boolean NOT NULL DEFAULT false, "valor_defecto" text, "orden" integer NOT NULL DEFAULT '0', "activo" boolean NOT NULL DEFAULT true, "validacion" jsonb, "visibilidad_condicional" jsonb, "requerido_condicional" jsonb, "texto_ayuda" text, "tipos_archivo_permitidos" text array, "tamano_max_archivo" integer, "multiple" boolean NOT NULL DEFAULT false, "metadata" jsonb, CONSTRAINT "UQ_b817aaf8e23eb928f76d530df49" UNIQUE ("formulario_version_id", "clave"), CONSTRAINT "PK_3804f50b17fc8ba2193ed1c37aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a11b32a4041f7c1a7bfaa170aa" ON "formularios_campos"  ("formulario_version_id") `);
        await queryRunner.query(`CREATE TABLE "formularios_campos_opciones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "campo_id" uuid NOT NULL, "valor" text NOT NULL, "etiqueta" text NOT NULL, "orden" integer NOT NULL DEFAULT '0', "activo" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_dca43d1797bc8f24b7dab26ee3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cfceba117f13b6535401c9f7a1" ON "formularios_campos_opciones"  ("campo_id") `);
        await queryRunner.query(`CREATE TYPE "public"."formularios_campos_condiciones_tipo_condicion_enum" AS ENUM('visibilidad', 'requerido')`);
        await queryRunner.query(`CREATE TYPE "public"."formularios_campos_condiciones_operador_enum" AS ENUM('igual', 'diferente', 'contiene', 'no_contiene', 'mayor_que', 'menor_que', 'vacio', 'no_vacio')`);
        await queryRunner.query(`CREATE TYPE "public"."formularios_campos_condiciones_conector_enum" AS ENUM('y', 'o')`);
        await queryRunner.query(`CREATE TABLE "formularios_campos_condiciones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "campo_id" uuid NOT NULL, "tipo_condicion" "public"."formularios_campos_condiciones_tipo_condicion_enum" NOT NULL, "campo_objetivo_clave" text NOT NULL, "operador" "public"."formularios_campos_condiciones_operador_enum" NOT NULL, "valor" text, "conector" "public"."formularios_campos_condiciones_conector_enum" NOT NULL DEFAULT 'y', "orden" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_5211a7ea429725c5be0ca1f9f5f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_28195a3b832b1f8bbbab7771b2" ON "formularios_campos_condiciones"  ("campo_id") `);
        await queryRunner.query(`CREATE TABLE "perfiles_ciudadano" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "fecha_actualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "usuario_id" uuid NOT NULL, "dpi" text, "nombres" text NOT NULL, "apellidos" text NOT NULL, "telefono" text, "fecha_nacimiento" date, "departamento_id" uuid, "municipio_id" uuid, "direccion" text, CONSTRAINT "REL_2e07a52948973c7f612d039ee2" UNIQUE ("usuario_id"), CONSTRAINT "PK_31095e85ed6b40675e72ba5ab49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2e07a52948973c7f612d039ee2" ON "perfiles_ciudadano"  ("usuario_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6abdd9f8a1635822416cae272e" ON "perfiles_ciudadano"  ("dpi") `);
        await queryRunner.query(`CREATE TYPE "public"."solicitudes_estado_enum" AS ENUM('borrador', 'enviada', 'recibida', 'en_revision', 'requiere_informacion', 'aprobada', 'rechazada', 'cancelada', 'completada')`);
        await queryRunner.query(`CREATE TABLE "solicitudes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "fecha_actualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "referencia_publica" text NOT NULL, "tramite_id" uuid NOT NULL, "formulario_version_id" uuid, "usuario_id" uuid NOT NULL, "estado" "public"."solicitudes_estado_enum" NOT NULL DEFAULT 'borrador', "datos" jsonb NOT NULL DEFAULT '{}'::jsonb, "enviada_en" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_8c7e99758c774b801853b538647" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_85b4602bf318ea8cddeb81c9fe" ON "solicitudes"  ("referencia_publica") `);
        await queryRunner.query(`CREATE INDEX "IDX_ab54e2c715f615176673e9ad8b" ON "solicitudes"  ("tramite_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_029c8c9b698def04343add529b" ON "solicitudes"  ("formulario_version_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_42802d7cdc2a5197f420571852" ON "solicitudes"  ("usuario_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d3d19f7c369601691999a4f34b" ON "solicitudes"  ("estado") `);
        await queryRunner.query(`CREATE TABLE "solicitudes_archivos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "solicitud_id" uuid NOT NULL, "campo_clave" text NOT NULL, "archivo_id" uuid NOT NULL, "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1356a101c08b030dc1a4812b07d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0b7eb4f99f339d9aa12401de39" ON "solicitudes_archivos"  ("solicitud_id") `);
        await queryRunner.query(`CREATE TABLE "solicitudes_historial_estado" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "solicitud_id" uuid NOT NULL, "estado_anterior" text, "estado_nuevo" text NOT NULL, "cambiado_por" uuid, "nota" text, "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_03bdbc988ed05708336197f77b2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9af3b9bb8c6d8a10b972813c02" ON "solicitudes_historial_estado"  ("solicitud_id") `);
        await queryRunner.query(`CREATE TABLE "archivos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bucket" text NOT NULL, "ruta" text NOT NULL, "nombre_original" text NOT NULL, "mime_type" text NOT NULL, "tamano_bytes" bigint NOT NULL, "checksum" text, "es_publico" boolean NOT NULL DEFAULT false, "subido_por" uuid, "entidad_tipo" text, "entidad_id" uuid, "metadata" jsonb, "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5609463cf53fb524304c926ad2d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "archivos_versiones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "archivo_id" uuid NOT NULL, "version" integer NOT NULL, "ruta" text NOT NULL, "tamano_bytes" bigint NOT NULL, "checksum" text, "subido_por" uuid, "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_82cbb627b1d8cc6900adf169ad7" UNIQUE ("archivo_id", "version"), CONSTRAINT "PK_3e7b3e265d58f3c381a3ba24c86" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8aee107508282beec23b98d0af" ON "archivos_versiones"  ("archivo_id") `);
        await queryRunner.query(`CREATE TABLE "registros_auditoria" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "usuario_id" uuid, "accion" text NOT NULL, "entidad" text NOT NULL, "entidad_id" text, "valores_anteriores" jsonb, "valores_nuevos" jsonb, "ip" inet, "user_agent" text, "request_id" text, "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_52a47d9f5f33f509ae83e56a747" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d6689562c5d3417485e11acb63" ON "registros_auditoria"  ("usuario_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_75c6a33f474b165b8df600cde1" ON "registros_auditoria"  ("entidad") `);
        await queryRunner.query(`CREATE INDEX "IDX_c4912b389bed3e1f6714c82604" ON "registros_auditoria"  ("fecha_creacion") `);
        await queryRunner.query(`CREATE TYPE "public"."notificaciones_canal_enum" AS ENUM('email', 'web', 'sms', 'whatsapp')`);
        await queryRunner.query(`CREATE TABLE "notificaciones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "usuario_id" uuid NOT NULL, "tipo" text NOT NULL, "canal" "public"."notificaciones_canal_enum" NOT NULL DEFAULT 'web', "titulo" text NOT NULL, "mensaje" text NOT NULL, "entidad_tipo" text, "entidad_id" uuid, "leida_en" TIMESTAMP WITH TIME ZONE, "enviada_en" TIMESTAMP WITH TIME ZONE, "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a9d32a419ff58b53a38b5ef85d4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2c6341d5bd206ff522b35aa6b6" ON "notificaciones"  ("usuario_id") `);
        await queryRunner.query(`CREATE TABLE "configuracion_sistema" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clave" text NOT NULL, "valor" jsonb NOT NULL, "descripcion" text, "actualizado_por" uuid, "fecha_actualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a039ed622dc643e8374d4e1a4d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0e9b47db25c1b7916c685fbb31" ON "configuracion_sistema"  ("clave") `);
        await queryRunner.query(`CREATE TYPE "public"."quejas_denuncias_tipo_enum" AS ENUM('queja', 'denuncia', 'informacion_incorrecta', 'sugerencia')`);
        await queryRunner.query(`CREATE TYPE "public"."quejas_denuncias_estado_enum" AS ENUM('abierta', 'en_proceso', 'resuelta', 'cerrada')`);
        await queryRunner.query(`CREATE TABLE "quejas_denuncias" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fecha_creacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "fecha_actualizacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tramite_id" uuid, "usuario_id" uuid, "tipo" "public"."quejas_denuncias_tipo_enum" NOT NULL DEFAULT 'queja', "descripcion" text NOT NULL, "contacto" text, "estado" "public"."quejas_denuncias_estado_enum" NOT NULL DEFAULT 'abierta', "respuesta" text, "atendido_por" uuid, CONSTRAINT "PK_0911950e041c476aae20c02e10e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b94555a52eb434506ecee3b2e0" ON "quejas_denuncias"  ("tramite_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e994d7110e230bff6d33461cfd" ON "quejas_denuncias"  ("usuario_id") `);
        await queryRunner.query(`ALTER TABLE "roles_permisos" ADD CONSTRAINT "FK_dc3cfbcce511233d4bef92d7e3b" FOREIGN KEY ("rol_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles_permisos" ADD CONSTRAINT "FK_ef10d9983fcb45f0024cc7000d3" FOREIGN KEY ("permiso_id") REFERENCES "permisos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_roles" ADD CONSTRAINT "FK_2c14b9e5e2d0cf077fa4dd33502" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_roles" ADD CONSTRAINT "FK_425dfd009aeeee0c08af9a67a37" FOREIGN KEY ("rol_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_roles" ADD CONSTRAINT "FK_aeab9942770118a43c775d15f13" FOREIGN KEY ("institucion_id") REFERENCES "instituciones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sesiones" ADD CONSTRAINT "FK_be14eb22d2e8fbf2ca6c3fe0d56" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ca207b81ff4fdef23d67064c17" FOREIGN KEY ("sesion_id") REFERENCES "sesiones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "llaves_api" ADD CONSTRAINT "FK_f291436142c2b81fa077a77f158" FOREIGN KEY ("propietario_usuario_id") REFERENCES "usuarios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "llaves_api_scopes" ADD CONSTRAINT "FK_105947105ef5ba0ed4a934b397f" FOREIGN KEY ("llave_api_id") REFERENCES "llaves_api"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "municipios" ADD CONSTRAINT "FK_cfc60523878116f625631f0e251" FOREIGN KEY ("departamento_id") REFERENCES "departamentos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instituciones_contactos" ADD CONSTRAINT "FK_e4b6487ae036dbac881c969ed3d" FOREIGN KEY ("institucion_id") REFERENCES "instituciones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instituciones_direcciones" ADD CONSTRAINT "FK_7f62270c608af6385526ab2935e" FOREIGN KEY ("institucion_id") REFERENCES "instituciones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instituciones_direcciones" ADD CONSTRAINT "FK_fd5192cae58364c336026022171" FOREIGN KEY ("departamento_id") REFERENCES "departamentos"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "instituciones_direcciones" ADD CONSTRAINT "FK_a215c545420317305f8ce7b5838" FOREIGN KEY ("municipio_id") REFERENCES "municipios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categorias_traducciones" ADD CONSTRAINT "FK_6bf3298f3a0a23605b1587cfb7c" FOREIGN KEY ("categoria_id") REFERENCES "categorias"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categorias_traducciones" ADD CONSTRAINT "FK_527ab82a85e09fba0470d9c4dc8" FOREIGN KEY ("idioma_id") REFERENCES "idiomas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites" ADD CONSTRAINT "FK_5eec71d25c15ca645497b9deff4" FOREIGN KEY ("institucion_id") REFERENCES "instituciones"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites" ADD CONSTRAINT "FK_806a4b9aa942e2d00c63ecfb8e1" FOREIGN KEY ("departamento_id") REFERENCES "departamentos"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites" ADD CONSTRAINT "FK_bb0c86da1593335baf54d9689a5" FOREIGN KEY ("municipio_id") REFERENCES "municipios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites_categorias" ADD CONSTRAINT "FK_1c00d9a6655a1324e8e8d00d7c3" FOREIGN KEY ("tramite_id") REFERENCES "tramites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites_categorias" ADD CONSTRAINT "FK_ed31569a06d7fb6079d05faabaf" FOREIGN KEY ("categoria_id") REFERENCES "categorias"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites_traducciones" ADD CONSTRAINT "FK_a451860420a30fcff54859804f2" FOREIGN KEY ("tramite_id") REFERENCES "tramites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites_traducciones" ADD CONSTRAINT "FK_85680d7cb03faf0049b16ab78e2" FOREIGN KEY ("idioma_id") REFERENCES "idiomas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites_historial_estado" ADD CONSTRAINT "FK_31b34a542bfefa0741820fe82f9" FOREIGN KEY ("tramite_id") REFERENCES "tramites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites_requisitos" ADD CONSTRAINT "FK_b8be3ac0ad1b1e0e9b77b6d7351" FOREIGN KEY ("tramite_id") REFERENCES "tramites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites_pasos" ADD CONSTRAINT "FK_c9ed0201065b146538ae7b91785" FOREIGN KEY ("tramite_id") REFERENCES "tramites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites_normativas" ADD CONSTRAINT "FK_5cd69d7d48ac0625ef0c9335559" FOREIGN KEY ("tramite_id") REFERENCES "tramites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites_enlaces" ADD CONSTRAINT "FK_42eb2e58870c320be7df4616ba1" FOREIGN KEY ("tramite_id") REFERENCES "tramites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites_costos" ADD CONSTRAINT "FK_284e34f923eed08301debee313a" FOREIGN KEY ("tramite_id") REFERENCES "tramites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites_tiempos" ADD CONSTRAINT "FK_e35c18a08cc37cce6e3f334d795" FOREIGN KEY ("tramite_id") REFERENCES "tramites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites_disponibilidad" ADD CONSTRAINT "FK_f03904a0ec8011ca602f6c6c7f1" FOREIGN KEY ("tramite_id") REFERENCES "tramites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites_versiones" ADD CONSTRAINT "FK_0f8d4b0664a1e6b338aae9a171c" FOREIGN KEY ("tramite_id") REFERENCES "tramites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites_integraciones" ADD CONSTRAINT "FK_e144260cf0bbc965925854716d3" FOREIGN KEY ("tramite_id") REFERENCES "tramites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites_videos_senas" ADD CONSTRAINT "FK_c835f3a2b9097b7a7d01f107198" FOREIGN KEY ("tramite_id") REFERENCES "tramites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites_recursos_accesibilidad" ADD CONSTRAINT "FK_03173731e3505b43c33eed386af" FOREIGN KEY ("tramite_id") REFERENCES "tramites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tramites_recursos_accesibilidad" ADD CONSTRAINT "FK_e06b8d825208c25221fd56f0f0c" FOREIGN KEY ("idioma_id") REFERENCES "idiomas"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "formularios" ADD CONSTRAINT "FK_47c769c3b433d16c9f24c2bf7a9" FOREIGN KEY ("tramite_id") REFERENCES "tramites"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "formularios_versiones" ADD CONSTRAINT "FK_b5869ca4c77e7dffaa0d0e1e759" FOREIGN KEY ("formulario_id") REFERENCES "formularios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "formularios_secciones" ADD CONSTRAINT "FK_70f19441de0564b6ab281c28519" FOREIGN KEY ("formulario_version_id") REFERENCES "formularios_versiones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "formularios_campos" ADD CONSTRAINT "FK_a11b32a4041f7c1a7bfaa170aaf" FOREIGN KEY ("formulario_version_id") REFERENCES "formularios_versiones"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "formularios_campos" ADD CONSTRAINT "FK_e50ce484505d71dd9d0af37aeb9" FOREIGN KEY ("seccion_id") REFERENCES "formularios_secciones"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "formularios_campos_opciones" ADD CONSTRAINT "FK_cfceba117f13b6535401c9f7a1a" FOREIGN KEY ("campo_id") REFERENCES "formularios_campos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "formularios_campos_condiciones" ADD CONSTRAINT "FK_28195a3b832b1f8bbbab7771b22" FOREIGN KEY ("campo_id") REFERENCES "formularios_campos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "perfiles_ciudadano" ADD CONSTRAINT "FK_2e07a52948973c7f612d039ee24" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "perfiles_ciudadano" ADD CONSTRAINT "FK_cf0b83529690a169d4b9dc720c8" FOREIGN KEY ("departamento_id") REFERENCES "departamentos"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "perfiles_ciudadano" ADD CONSTRAINT "FK_6506b6be480c45e02f82d3f7efc" FOREIGN KEY ("municipio_id") REFERENCES "municipios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "solicitudes" ADD CONSTRAINT "FK_ab54e2c715f615176673e9ad8b5" FOREIGN KEY ("tramite_id") REFERENCES "tramites"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "solicitudes" ADD CONSTRAINT "FK_029c8c9b698def04343add529b9" FOREIGN KEY ("formulario_version_id") REFERENCES "formularios_versiones"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "solicitudes" ADD CONSTRAINT "FK_42802d7cdc2a5197f4205718528" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "solicitudes_archivos" ADD CONSTRAINT "FK_0b7eb4f99f339d9aa12401de395" FOREIGN KEY ("solicitud_id") REFERENCES "solicitudes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "solicitudes_archivos" ADD CONSTRAINT "FK_045dba1621d9df228477778c6c1" FOREIGN KEY ("archivo_id") REFERENCES "archivos"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "solicitudes_historial_estado" ADD CONSTRAINT "FK_9af3b9bb8c6d8a10b972813c02b" FOREIGN KEY ("solicitud_id") REFERENCES "solicitudes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "archivos_versiones" ADD CONSTRAINT "FK_8aee107508282beec23b98d0af5" FOREIGN KEY ("archivo_id") REFERENCES "archivos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notificaciones" ADD CONSTRAINT "FK_2c6341d5bd206ff522b35aa6b69" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quejas_denuncias" ADD CONSTRAINT "FK_b94555a52eb434506ecee3b2e0e" FOREIGN KEY ("tramite_id") REFERENCES "tramites"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quejas_denuncias" ADD CONSTRAINT "FK_e994d7110e230bff6d33461cfd3" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "quejas_denuncias" DROP CONSTRAINT "FK_e994d7110e230bff6d33461cfd3"`);
        await queryRunner.query(`ALTER TABLE "quejas_denuncias" DROP CONSTRAINT "FK_b94555a52eb434506ecee3b2e0e"`);
        await queryRunner.query(`ALTER TABLE "notificaciones" DROP CONSTRAINT "FK_2c6341d5bd206ff522b35aa6b69"`);
        await queryRunner.query(`ALTER TABLE "archivos_versiones" DROP CONSTRAINT "FK_8aee107508282beec23b98d0af5"`);
        await queryRunner.query(`ALTER TABLE "solicitudes_historial_estado" DROP CONSTRAINT "FK_9af3b9bb8c6d8a10b972813c02b"`);
        await queryRunner.query(`ALTER TABLE "solicitudes_archivos" DROP CONSTRAINT "FK_045dba1621d9df228477778c6c1"`);
        await queryRunner.query(`ALTER TABLE "solicitudes_archivos" DROP CONSTRAINT "FK_0b7eb4f99f339d9aa12401de395"`);
        await queryRunner.query(`ALTER TABLE "solicitudes" DROP CONSTRAINT "FK_42802d7cdc2a5197f4205718528"`);
        await queryRunner.query(`ALTER TABLE "solicitudes" DROP CONSTRAINT "FK_029c8c9b698def04343add529b9"`);
        await queryRunner.query(`ALTER TABLE "solicitudes" DROP CONSTRAINT "FK_ab54e2c715f615176673e9ad8b5"`);
        await queryRunner.query(`ALTER TABLE "perfiles_ciudadano" DROP CONSTRAINT "FK_6506b6be480c45e02f82d3f7efc"`);
        await queryRunner.query(`ALTER TABLE "perfiles_ciudadano" DROP CONSTRAINT "FK_cf0b83529690a169d4b9dc720c8"`);
        await queryRunner.query(`ALTER TABLE "perfiles_ciudadano" DROP CONSTRAINT "FK_2e07a52948973c7f612d039ee24"`);
        await queryRunner.query(`ALTER TABLE "formularios_campos_condiciones" DROP CONSTRAINT "FK_28195a3b832b1f8bbbab7771b22"`);
        await queryRunner.query(`ALTER TABLE "formularios_campos_opciones" DROP CONSTRAINT "FK_cfceba117f13b6535401c9f7a1a"`);
        await queryRunner.query(`ALTER TABLE "formularios_campos" DROP CONSTRAINT "FK_e50ce484505d71dd9d0af37aeb9"`);
        await queryRunner.query(`ALTER TABLE "formularios_campos" DROP CONSTRAINT "FK_a11b32a4041f7c1a7bfaa170aaf"`);
        await queryRunner.query(`ALTER TABLE "formularios_secciones" DROP CONSTRAINT "FK_70f19441de0564b6ab281c28519"`);
        await queryRunner.query(`ALTER TABLE "formularios_versiones" DROP CONSTRAINT "FK_b5869ca4c77e7dffaa0d0e1e759"`);
        await queryRunner.query(`ALTER TABLE "formularios" DROP CONSTRAINT "FK_47c769c3b433d16c9f24c2bf7a9"`);
        await queryRunner.query(`ALTER TABLE "tramites_recursos_accesibilidad" DROP CONSTRAINT "FK_e06b8d825208c25221fd56f0f0c"`);
        await queryRunner.query(`ALTER TABLE "tramites_recursos_accesibilidad" DROP CONSTRAINT "FK_03173731e3505b43c33eed386af"`);
        await queryRunner.query(`ALTER TABLE "tramites_videos_senas" DROP CONSTRAINT "FK_c835f3a2b9097b7a7d01f107198"`);
        await queryRunner.query(`ALTER TABLE "tramites_integraciones" DROP CONSTRAINT "FK_e144260cf0bbc965925854716d3"`);
        await queryRunner.query(`ALTER TABLE "tramites_versiones" DROP CONSTRAINT "FK_0f8d4b0664a1e6b338aae9a171c"`);
        await queryRunner.query(`ALTER TABLE "tramites_disponibilidad" DROP CONSTRAINT "FK_f03904a0ec8011ca602f6c6c7f1"`);
        await queryRunner.query(`ALTER TABLE "tramites_tiempos" DROP CONSTRAINT "FK_e35c18a08cc37cce6e3f334d795"`);
        await queryRunner.query(`ALTER TABLE "tramites_costos" DROP CONSTRAINT "FK_284e34f923eed08301debee313a"`);
        await queryRunner.query(`ALTER TABLE "tramites_enlaces" DROP CONSTRAINT "FK_42eb2e58870c320be7df4616ba1"`);
        await queryRunner.query(`ALTER TABLE "tramites_normativas" DROP CONSTRAINT "FK_5cd69d7d48ac0625ef0c9335559"`);
        await queryRunner.query(`ALTER TABLE "tramites_pasos" DROP CONSTRAINT "FK_c9ed0201065b146538ae7b91785"`);
        await queryRunner.query(`ALTER TABLE "tramites_requisitos" DROP CONSTRAINT "FK_b8be3ac0ad1b1e0e9b77b6d7351"`);
        await queryRunner.query(`ALTER TABLE "tramites_historial_estado" DROP CONSTRAINT "FK_31b34a542bfefa0741820fe82f9"`);
        await queryRunner.query(`ALTER TABLE "tramites_traducciones" DROP CONSTRAINT "FK_85680d7cb03faf0049b16ab78e2"`);
        await queryRunner.query(`ALTER TABLE "tramites_traducciones" DROP CONSTRAINT "FK_a451860420a30fcff54859804f2"`);
        await queryRunner.query(`ALTER TABLE "tramites_categorias" DROP CONSTRAINT "FK_ed31569a06d7fb6079d05faabaf"`);
        await queryRunner.query(`ALTER TABLE "tramites_categorias" DROP CONSTRAINT "FK_1c00d9a6655a1324e8e8d00d7c3"`);
        await queryRunner.query(`ALTER TABLE "tramites" DROP CONSTRAINT "FK_bb0c86da1593335baf54d9689a5"`);
        await queryRunner.query(`ALTER TABLE "tramites" DROP CONSTRAINT "FK_806a4b9aa942e2d00c63ecfb8e1"`);
        await queryRunner.query(`ALTER TABLE "tramites" DROP CONSTRAINT "FK_5eec71d25c15ca645497b9deff4"`);
        await queryRunner.query(`ALTER TABLE "categorias_traducciones" DROP CONSTRAINT "FK_527ab82a85e09fba0470d9c4dc8"`);
        await queryRunner.query(`ALTER TABLE "categorias_traducciones" DROP CONSTRAINT "FK_6bf3298f3a0a23605b1587cfb7c"`);
        await queryRunner.query(`ALTER TABLE "instituciones_direcciones" DROP CONSTRAINT "FK_a215c545420317305f8ce7b5838"`);
        await queryRunner.query(`ALTER TABLE "instituciones_direcciones" DROP CONSTRAINT "FK_fd5192cae58364c336026022171"`);
        await queryRunner.query(`ALTER TABLE "instituciones_direcciones" DROP CONSTRAINT "FK_7f62270c608af6385526ab2935e"`);
        await queryRunner.query(`ALTER TABLE "instituciones_contactos" DROP CONSTRAINT "FK_e4b6487ae036dbac881c969ed3d"`);
        await queryRunner.query(`ALTER TABLE "municipios" DROP CONSTRAINT "FK_cfc60523878116f625631f0e251"`);
        await queryRunner.query(`ALTER TABLE "llaves_api_scopes" DROP CONSTRAINT "FK_105947105ef5ba0ed4a934b397f"`);
        await queryRunner.query(`ALTER TABLE "llaves_api" DROP CONSTRAINT "FK_f291436142c2b81fa077a77f158"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ca207b81ff4fdef23d67064c17"`);
        await queryRunner.query(`ALTER TABLE "sesiones" DROP CONSTRAINT "FK_be14eb22d2e8fbf2ca6c3fe0d56"`);
        await queryRunner.query(`ALTER TABLE "usuarios_roles" DROP CONSTRAINT "FK_aeab9942770118a43c775d15f13"`);
        await queryRunner.query(`ALTER TABLE "usuarios_roles" DROP CONSTRAINT "FK_425dfd009aeeee0c08af9a67a37"`);
        await queryRunner.query(`ALTER TABLE "usuarios_roles" DROP CONSTRAINT "FK_2c14b9e5e2d0cf077fa4dd33502"`);
        await queryRunner.query(`ALTER TABLE "roles_permisos" DROP CONSTRAINT "FK_ef10d9983fcb45f0024cc7000d3"`);
        await queryRunner.query(`ALTER TABLE "roles_permisos" DROP CONSTRAINT "FK_dc3cfbcce511233d4bef92d7e3b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e994d7110e230bff6d33461cfd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b94555a52eb434506ecee3b2e0"`);
        await queryRunner.query(`DROP TABLE "quejas_denuncias"`);
        await queryRunner.query(`DROP TYPE "public"."quejas_denuncias_estado_enum"`);
        await queryRunner.query(`DROP TYPE "public"."quejas_denuncias_tipo_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e9b47db25c1b7916c685fbb31"`);
        await queryRunner.query(`DROP TABLE "configuracion_sistema"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c6341d5bd206ff522b35aa6b6"`);
        await queryRunner.query(`DROP TABLE "notificaciones"`);
        await queryRunner.query(`DROP TYPE "public"."notificaciones_canal_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4912b389bed3e1f6714c82604"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75c6a33f474b165b8df600cde1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6689562c5d3417485e11acb63"`);
        await queryRunner.query(`DROP TABLE "registros_auditoria"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8aee107508282beec23b98d0af"`);
        await queryRunner.query(`DROP TABLE "archivos_versiones"`);
        await queryRunner.query(`DROP TABLE "archivos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9af3b9bb8c6d8a10b972813c02"`);
        await queryRunner.query(`DROP TABLE "solicitudes_historial_estado"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b7eb4f99f339d9aa12401de39"`);
        await queryRunner.query(`DROP TABLE "solicitudes_archivos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d3d19f7c369601691999a4f34b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42802d7cdc2a5197f420571852"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_029c8c9b698def04343add529b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab54e2c715f615176673e9ad8b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85b4602bf318ea8cddeb81c9fe"`);
        await queryRunner.query(`DROP TABLE "solicitudes"`);
        await queryRunner.query(`DROP TYPE "public"."solicitudes_estado_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6abdd9f8a1635822416cae272e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e07a52948973c7f612d039ee2"`);
        await queryRunner.query(`DROP TABLE "perfiles_ciudadano"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_28195a3b832b1f8bbbab7771b2"`);
        await queryRunner.query(`DROP TABLE "formularios_campos_condiciones"`);
        await queryRunner.query(`DROP TYPE "public"."formularios_campos_condiciones_conector_enum"`);
        await queryRunner.query(`DROP TYPE "public"."formularios_campos_condiciones_operador_enum"`);
        await queryRunner.query(`DROP TYPE "public"."formularios_campos_condiciones_tipo_condicion_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfceba117f13b6535401c9f7a1"`);
        await queryRunner.query(`DROP TABLE "formularios_campos_opciones"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a11b32a4041f7c1a7bfaa170aa"`);
        await queryRunner.query(`DROP TABLE "formularios_campos"`);
        await queryRunner.query(`DROP TYPE "public"."formularios_campos_tipo_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70f19441de0564b6ab281c2851"`);
        await queryRunner.query(`DROP TABLE "formularios_secciones"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5869ca4c77e7dffaa0d0e1e75"`);
        await queryRunner.query(`DROP TABLE "formularios_versiones"`);
        await queryRunner.query(`DROP TYPE "public"."formularios_versiones_estado_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47c769c3b433d16c9f24c2bf7a"`);
        await queryRunner.query(`DROP TABLE "formularios"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_03173731e3505b43c33eed386a"`);
        await queryRunner.query(`DROP TABLE "tramites_recursos_accesibilidad"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_recursos_accesibilidad_estado_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_recursos_accesibilidad_tipo_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c835f3a2b9097b7a7d01f10719"`);
        await queryRunner.query(`DROP TABLE "tramites_videos_senas"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_videos_senas_estado_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cbc4d734c634c8078ec93e5a85"`);
        await queryRunner.query(`DROP TABLE "idiomas"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e144260cf0bbc965925854716d"`);
        await queryRunner.query(`DROP TABLE "tramites_integraciones"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_integraciones_tipo_auth_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_integraciones_tipo_integracion_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f8d4b0664a1e6b338aae9a171"`);
        await queryRunner.query(`DROP TABLE "tramites_versiones"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f03904a0ec8011ca602f6c6c7f"`);
        await queryRunner.query(`DROP TABLE "tramites_disponibilidad"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_disponibilidad_canal_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e35c18a08cc37cce6e3f334d79"`);
        await queryRunner.query(`DROP TABLE "tramites_tiempos"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_tiempos_unidad_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_284e34f923eed08301debee313"`);
        await queryRunner.query(`DROP TABLE "tramites_costos"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_costos_tipo_costo_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42eb2e58870c320be7df4616ba"`);
        await queryRunner.query(`DROP TABLE "tramites_enlaces"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_enlaces_tipo_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5cd69d7d48ac0625ef0c933555"`);
        await queryRunner.query(`DROP TABLE "tramites_normativas"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9ed0201065b146538ae7b9178"`);
        await queryRunner.query(`DROP TABLE "tramites_pasos"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_pasos_canal_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_pasos_parte_responsable_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8be3ac0ad1b1e0e9b77b6d735"`);
        await queryRunner.query(`DROP TABLE "tramites_requisitos"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_requisitos_tipo_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31b34a542bfefa0741820fe82f"`);
        await queryRunner.query(`DROP TABLE "tramites_historial_estado"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_historial_estado_estado_nuevo_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_historial_estado_estado_anterior_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85680d7cb03faf0049b16ab78e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a451860420a30fcff54859804f"`);
        await queryRunner.query(`DROP TABLE "tramites_traducciones"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_traducciones_estado_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed31569a06d7fb6079d05faaba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1c00d9a6655a1324e8e8d00d7c"`);
        await queryRunner.query(`DROP TABLE "tramites_categorias"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d4be5d74c734cfa8533f70fbb2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5eec71d25c15ca645497b9deff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e98a13d29d97c5dbbd38012ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1c80b0eec4e61714935290872e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5516120ac0363cd07913429117"`);
        await queryRunner.query(`DROP TABLE "tramites"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_tipo_fuente_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_calidad_datos_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_tiempo_respuesta_unidad_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_tipo_costo_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_modalidad_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_modo_ejecucion_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tramites_estado_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_527ab82a85e09fba0470d9c4dc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6bf3298f3a0a23605b1587cfb7"`);
        await queryRunner.query(`DROP TABLE "categorias_traducciones"`);
        await queryRunner.query(`DROP TYPE "public"."categorias_traducciones_estado_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7c32fbaefae4a73773e52c316"`);
        await queryRunner.query(`DROP TABLE "categorias"`);
        await queryRunner.query(`DROP TYPE "public"."categorias_estado_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f62270c608af6385526ab2935"`);
        await queryRunner.query(`DROP TABLE "instituciones_direcciones"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4b6487ae036dbac881c969ed3"`);
        await queryRunner.query(`DROP TABLE "instituciones_contactos"`);
        await queryRunner.query(`DROP TYPE "public"."instituciones_contactos_tipo_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26432f4088d2b4315c77342120"`);
        await queryRunner.query(`DROP TABLE "instituciones"`);
        await queryRunner.query(`DROP TYPE "public"."instituciones_estado_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfc60523878116f625631f0e25"`);
        await queryRunner.query(`DROP TABLE "municipios"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f48b6363c3ee466eaa21dae234"`);
        await queryRunner.query(`DROP TABLE "departamentos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_105947105ef5ba0ed4a934b397"`);
        await queryRunner.query(`DROP TABLE "llaves_api_scopes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1bfaf1ece297bf10a420b96fd5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_308b63c6ca11d126e7abc6052c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f291436142c2b81fa077a77f15"`);
        await queryRunner.query(`DROP TABLE "llaves_api"`);
        await queryRunner.query(`DROP TYPE "public"."llaves_api_estado_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b61ca8d3b37ca11928995f2277"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ca207b81ff4fdef23d67064c1"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be14eb22d2e8fbf2ca6c3fe0d5"`);
        await queryRunner.query(`DROP TABLE "sesiones"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aeab9942770118a43c775d15f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_425dfd009aeeee0c08af9a67a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c14b9e5e2d0cf077fa4dd3350"`);
        await queryRunner.query(`DROP TABLE "usuarios_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef10d9983fcb45f0024cc7000d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc3cfbcce511233d4bef92d7e3"`);
        await queryRunner.query(`DROP TABLE "roles_permisos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0da1398fc247170cac89e49205"`);
        await queryRunner.query(`DROP TABLE "permisos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6c91cc0373d07c0884887ae51"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_446adfc18b35418aac32ae0b7b"`);
        await queryRunner.query(`DROP TABLE "usuarios"`);
        await queryRunner.query(`DROP TYPE "public"."usuarios_estado_enum"`);
    }

}
